version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: imageapp
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Express App Service
  app:
    build: .
    container_name: image-app
    ports:
      - "3001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/imageapp
      - JWT_SECRET=your_super_secret_jwt_key_here_for_docker_deployment
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
